### ISSUE TITLE
Migrate CASA cabs to casatools 

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/cult-cargo#2]
The package is available on pypi!  as [casatools](https://pypi.org/project/casatools/)

I never thought I'd live to see the day

![Screenshot from 2023-03-27 18-28-51](https://user-images.githubusercontent.com/6624280/228005671-decccdde-8119-488e-bf3c-8e5110898827.png)

It should be an `IOError` but, baby steps.

**Comment by o-smirnov** [comment]
So a couple more points:

* we probably want to keep support for old-style CASA tasks, right? There have been many instances in the past when we needed to run some vintage CASAs due to breakage or some functionality changes (the French say 1948 was the best year for ~Bordeaux~gaincal!...)

* cab names can have dots in them, so ``casa.listobs`` seems like the obvious naming convention. But we need to distinguish old-school CASA from new-school. ``casa.legacy.listobs`` vs ``casa.listobs``, perhaps?

* don't forget about ``_use`` and ``_include`` (see my shiny new Stimela docs for details). We can define the cab schemas in one place, and reuse them for both old and new-style cab definitions.
